/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWorkspaceRouteImport } from './routes/dashboard.workspace'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardTrainingRouteImport } from './routes/dashboard.training'
import { Route as DashboardSubmissionsRouteImport } from './routes/dashboard.submissions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMyLeadsRouteImport } from './routes/dashboard.my-leads'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard.marketing'
import { Route as DashboardLeadboardRouteImport } from './routes/dashboard.leadboard'
import { Route as DashboardHrmsRouteImport } from './routes/dashboard.hrms'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard.earnings'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardCasesRouteImport } from './routes/dashboard.cases'
import { Route as DashboardCallsRouteImport } from './routes/dashboard.calls'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardMarketingIndexRouteImport } from './routes/dashboard.marketing.index'
import { Route as DashboardHrmsIndexRouteImport } from './routes/dashboard.hrms.index'
import { Route as DashboardMarketingWhatsappRouteImport } from './routes/dashboard.marketing.whatsapp'
import { Route as DashboardMarketingReferralRouteImport } from './routes/dashboard.marketing.referral'
import { Route as DashboardMarketingReelsRouteImport } from './routes/dashboard.marketing.reels'
import { Route as DashboardMarketingPostsRouteImport } from './routes/dashboard.marketing.posts'
import { Route as DashboardMarketingOneclickRouteImport } from './routes/dashboard.marketing.oneclick'
import { Route as DashboardMarketingCardRouteImport } from './routes/dashboard.marketing.card'
import { Route as DashboardHrmsPayrollRouteImport } from './routes/dashboard.hrms.payroll'
import { Route as DashboardHrmsBillingRouteImport } from './routes/dashboard.hrms.billing'
import { Route as DashboardHrmsAttendanceRouteImport } from './routes/dashboard.hrms.attendance'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminPricingRouteImport } from './routes/dashboard.admin.pricing'
import { Route as DashboardAdminPayoutsRouteImport } from './routes/dashboard.admin.payouts'
import { Route as DashboardAdminMarketingMediaRouteImport } from './routes/dashboard.admin.marketing-media'
import { Route as DashboardAdminMarketingRouteImport } from './routes/dashboard.admin.marketing'
import { Route as DashboardAdminLeadsRouteImport } from './routes/dashboard.admin.leads'
import { Route as DashboardHrmsPayslipsIndexRouteImport } from './routes/dashboard.hrms.payslips.index'
import { Route as DashboardMyLeadsIdApplyRouteImport } from './routes/dashboard.my-leads.$id.apply'
import { Route as DashboardHrmsPayslipsIdRouteImport } from './routes/dashboard.hrms.payslips.$id'
import { Route as DashboardHrmsEmployeesIdRouteImport } from './routes/dashboard.hrms.employees.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceRoute = DashboardWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrainingRoute = DashboardTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyLeadsRoute = DashboardMyLeadsRouteImport.update({
  id: '/my-leads',
  path: '/my-leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadboardRoute = DashboardLeadboardRouteImport.update({
  id: '/leadboard',
  path: '/leadboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHrmsRoute = DashboardHrmsRouteImport.update({
  id: '/hrms',
  path: '/hrms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesRoute = DashboardCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCallsRoute = DashboardCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketingIndexRoute = DashboardMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMarketingRoute,
} as any)
const DashboardHrmsIndexRoute = DashboardHrmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardHrmsRoute,
} as any)
const DashboardMarketingWhatsappRoute =
  DashboardMarketingWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => DashboardMarketingRoute,
  } as any)
const DashboardMarketingReferralRoute =
  DashboardMarketingReferralRouteImport.update({
    id: '/referral',
    path: '/referral',
    getParentRoute: () => DashboardMarketingRoute,
  } as any)
const DashboardMarketingReelsRoute = DashboardMarketingReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => DashboardMarketingRoute,
} as any)
const DashboardMarketingPostsRoute = DashboardMarketingPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => DashboardMarketingRoute,
} as any)
const DashboardMarketingOneclickRoute =
  DashboardMarketingOneclickRouteImport.update({
    id: '/oneclick',
    path: '/oneclick',
    getParentRoute: () => DashboardMarketingRoute,
  } as any)
const DashboardMarketingCardRoute = DashboardMarketingCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => DashboardMarketingRoute,
} as any)
const DashboardHrmsPayrollRoute = DashboardHrmsPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => DashboardHrmsRoute,
} as any)
const DashboardHrmsBillingRoute = DashboardHrmsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardHrmsRoute,
} as any)
const DashboardHrmsAttendanceRoute = DashboardHrmsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardHrmsRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPricingRoute = DashboardAdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPayoutsRoute = DashboardAdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminMarketingMediaRoute =
  DashboardAdminMarketingMediaRouteImport.update({
    id: '/admin/marketing-media',
    path: '/admin/marketing-media',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminMarketingRoute = DashboardAdminMarketingRouteImport.update({
  id: '/admin/marketing',
  path: '/admin/marketing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminLeadsRoute = DashboardAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHrmsPayslipsIndexRoute =
  DashboardHrmsPayslipsIndexRouteImport.update({
    id: '/payslips/',
    path: '/payslips/',
    getParentRoute: () => DashboardHrmsRoute,
  } as any)
const DashboardMyLeadsIdApplyRoute = DashboardMyLeadsIdApplyRouteImport.update({
  id: '/$id/apply',
  path: '/$id/apply',
  getParentRoute: () => DashboardMyLeadsRoute,
} as any)
const DashboardHrmsPayslipsIdRoute = DashboardHrmsPayslipsIdRouteImport.update({
  id: '/payslips/$id',
  path: '/payslips/$id',
  getParentRoute: () => DashboardHrmsRoute,
} as any)
const DashboardHrmsEmployeesIdRoute =
  DashboardHrmsEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => DashboardHrmsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/hrms': typeof DashboardHrmsRouteWithChildren
  '/dashboard/leadboard': typeof DashboardLeadboardRoute
  '/dashboard/marketing': typeof DashboardMarketingRouteWithChildren
  '/dashboard/my-leads': typeof DashboardMyLeadsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRoute
  '/dashboard/admin/marketing': typeof DashboardAdminMarketingRoute
  '/dashboard/admin/marketing-media': typeof DashboardAdminMarketingMediaRoute
  '/dashboard/admin/payouts': typeof DashboardAdminPayoutsRoute
  '/dashboard/admin/pricing': typeof DashboardAdminPricingRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/hrms/attendance': typeof DashboardHrmsAttendanceRoute
  '/dashboard/hrms/billing': typeof DashboardHrmsBillingRoute
  '/dashboard/hrms/payroll': typeof DashboardHrmsPayrollRoute
  '/dashboard/marketing/card': typeof DashboardMarketingCardRoute
  '/dashboard/marketing/oneclick': typeof DashboardMarketingOneclickRoute
  '/dashboard/marketing/posts': typeof DashboardMarketingPostsRoute
  '/dashboard/marketing/reels': typeof DashboardMarketingReelsRoute
  '/dashboard/marketing/referral': typeof DashboardMarketingReferralRoute
  '/dashboard/marketing/whatsapp': typeof DashboardMarketingWhatsappRoute
  '/dashboard/hrms/': typeof DashboardHrmsIndexRoute
  '/dashboard/marketing/': typeof DashboardMarketingIndexRoute
  '/dashboard/hrms/employees/$id': typeof DashboardHrmsEmployeesIdRoute
  '/dashboard/hrms/payslips/$id': typeof DashboardHrmsPayslipsIdRoute
  '/dashboard/my-leads/$id/apply': typeof DashboardMyLeadsIdApplyRoute
  '/dashboard/hrms/payslips/': typeof DashboardHrmsPayslipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/leadboard': typeof DashboardLeadboardRoute
  '/dashboard/my-leads': typeof DashboardMyLeadsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRoute
  '/dashboard/admin/marketing': typeof DashboardAdminMarketingRoute
  '/dashboard/admin/marketing-media': typeof DashboardAdminMarketingMediaRoute
  '/dashboard/admin/payouts': typeof DashboardAdminPayoutsRoute
  '/dashboard/admin/pricing': typeof DashboardAdminPricingRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/hrms/attendance': typeof DashboardHrmsAttendanceRoute
  '/dashboard/hrms/billing': typeof DashboardHrmsBillingRoute
  '/dashboard/hrms/payroll': typeof DashboardHrmsPayrollRoute
  '/dashboard/marketing/card': typeof DashboardMarketingCardRoute
  '/dashboard/marketing/oneclick': typeof DashboardMarketingOneclickRoute
  '/dashboard/marketing/posts': typeof DashboardMarketingPostsRoute
  '/dashboard/marketing/reels': typeof DashboardMarketingReelsRoute
  '/dashboard/marketing/referral': typeof DashboardMarketingReferralRoute
  '/dashboard/marketing/whatsapp': typeof DashboardMarketingWhatsappRoute
  '/dashboard/hrms': typeof DashboardHrmsIndexRoute
  '/dashboard/marketing': typeof DashboardMarketingIndexRoute
  '/dashboard/hrms/employees/$id': typeof DashboardHrmsEmployeesIdRoute
  '/dashboard/hrms/payslips/$id': typeof DashboardHrmsPayslipsIdRoute
  '/dashboard/my-leads/$id/apply': typeof DashboardMyLeadsIdApplyRoute
  '/dashboard/hrms/payslips': typeof DashboardHrmsPayslipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/cases': typeof DashboardCasesRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/hrms': typeof DashboardHrmsRouteWithChildren
  '/dashboard/leadboard': typeof DashboardLeadboardRoute
  '/dashboard/marketing': typeof DashboardMarketingRouteWithChildren
  '/dashboard/my-leads': typeof DashboardMyLeadsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRoute
  '/dashboard/admin/marketing': typeof DashboardAdminMarketingRoute
  '/dashboard/admin/marketing-media': typeof DashboardAdminMarketingMediaRoute
  '/dashboard/admin/payouts': typeof DashboardAdminPayoutsRoute
  '/dashboard/admin/pricing': typeof DashboardAdminPricingRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/hrms/attendance': typeof DashboardHrmsAttendanceRoute
  '/dashboard/hrms/billing': typeof DashboardHrmsBillingRoute
  '/dashboard/hrms/payroll': typeof DashboardHrmsPayrollRoute
  '/dashboard/marketing/card': typeof DashboardMarketingCardRoute
  '/dashboard/marketing/oneclick': typeof DashboardMarketingOneclickRoute
  '/dashboard/marketing/posts': typeof DashboardMarketingPostsRoute
  '/dashboard/marketing/reels': typeof DashboardMarketingReelsRoute
  '/dashboard/marketing/referral': typeof DashboardMarketingReferralRoute
  '/dashboard/marketing/whatsapp': typeof DashboardMarketingWhatsappRoute
  '/dashboard/hrms/': typeof DashboardHrmsIndexRoute
  '/dashboard/marketing/': typeof DashboardMarketingIndexRoute
  '/dashboard/hrms/employees/$id': typeof DashboardHrmsEmployeesIdRoute
  '/dashboard/hrms/payslips/$id': typeof DashboardHrmsPayslipsIdRoute
  '/dashboard/my-leads/$id/apply': typeof DashboardMyLeadsIdApplyRoute
  '/dashboard/hrms/payslips/': typeof DashboardHrmsPayslipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/cases'
    | '/dashboard/community'
    | '/dashboard/earnings'
    | '/dashboard/hrms'
    | '/dashboard/leadboard'
    | '/dashboard/marketing'
    | '/dashboard/my-leads'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/training'
    | '/dashboard/wallet'
    | '/dashboard/workspace'
    | '/dashboard/'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/marketing'
    | '/dashboard/admin/marketing-media'
    | '/dashboard/admin/payouts'
    | '/dashboard/admin/pricing'
    | '/dashboard/admin/users'
    | '/dashboard/hrms/attendance'
    | '/dashboard/hrms/billing'
    | '/dashboard/hrms/payroll'
    | '/dashboard/marketing/card'
    | '/dashboard/marketing/oneclick'
    | '/dashboard/marketing/posts'
    | '/dashboard/marketing/reels'
    | '/dashboard/marketing/referral'
    | '/dashboard/marketing/whatsapp'
    | '/dashboard/hrms/'
    | '/dashboard/marketing/'
    | '/dashboard/hrms/employees/$id'
    | '/dashboard/hrms/payslips/$id'
    | '/dashboard/my-leads/$id/apply'
    | '/dashboard/hrms/payslips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/cases'
    | '/dashboard/community'
    | '/dashboard/earnings'
    | '/dashboard/leadboard'
    | '/dashboard/my-leads'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/training'
    | '/dashboard/wallet'
    | '/dashboard/workspace'
    | '/dashboard'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/marketing'
    | '/dashboard/admin/marketing-media'
    | '/dashboard/admin/payouts'
    | '/dashboard/admin/pricing'
    | '/dashboard/admin/users'
    | '/dashboard/hrms/attendance'
    | '/dashboard/hrms/billing'
    | '/dashboard/hrms/payroll'
    | '/dashboard/marketing/card'
    | '/dashboard/marketing/oneclick'
    | '/dashboard/marketing/posts'
    | '/dashboard/marketing/reels'
    | '/dashboard/marketing/referral'
    | '/dashboard/marketing/whatsapp'
    | '/dashboard/hrms'
    | '/dashboard/marketing'
    | '/dashboard/hrms/employees/$id'
    | '/dashboard/hrms/payslips/$id'
    | '/dashboard/my-leads/$id/apply'
    | '/dashboard/hrms/payslips'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/dashboard/billing'
    | '/dashboard/calls'
    | '/dashboard/cases'
    | '/dashboard/community'
    | '/dashboard/earnings'
    | '/dashboard/hrms'
    | '/dashboard/leadboard'
    | '/dashboard/marketing'
    | '/dashboard/my-leads'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/training'
    | '/dashboard/wallet'
    | '/dashboard/workspace'
    | '/dashboard/'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/marketing'
    | '/dashboard/admin/marketing-media'
    | '/dashboard/admin/payouts'
    | '/dashboard/admin/pricing'
    | '/dashboard/admin/users'
    | '/dashboard/hrms/attendance'
    | '/dashboard/hrms/billing'
    | '/dashboard/hrms/payroll'
    | '/dashboard/marketing/card'
    | '/dashboard/marketing/oneclick'
    | '/dashboard/marketing/posts'
    | '/dashboard/marketing/reels'
    | '/dashboard/marketing/referral'
    | '/dashboard/marketing/whatsapp'
    | '/dashboard/hrms/'
    | '/dashboard/marketing/'
    | '/dashboard/hrms/employees/$id'
    | '/dashboard/hrms/payslips/$id'
    | '/dashboard/my-leads/$id/apply'
    | '/dashboard/hrms/payslips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workspace': {
      id: '/dashboard/workspace'
      path: '/workspace'
      fullPath: '/dashboard/workspace'
      preLoaderRoute: typeof DashboardWorkspaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/training': {
      id: '/dashboard/training'
      path: '/training'
      fullPath: '/dashboard/training'
      preLoaderRoute: typeof DashboardTrainingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions': {
      id: '/dashboard/submissions'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-leads': {
      id: '/dashboard/my-leads'
      path: '/my-leads'
      fullPath: '/dashboard/my-leads'
      preLoaderRoute: typeof DashboardMyLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leadboard': {
      id: '/dashboard/leadboard'
      path: '/leadboard'
      fullPath: '/dashboard/leadboard'
      preLoaderRoute: typeof DashboardLeadboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hrms': {
      id: '/dashboard/hrms'
      path: '/hrms'
      fullPath: '/dashboard/hrms'
      preLoaderRoute: typeof DashboardHrmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases': {
      id: '/dashboard/cases'
      path: '/cases'
      fullPath: '/dashboard/cases'
      preLoaderRoute: typeof DashboardCasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calls': {
      id: '/dashboard/calls'
      path: '/calls'
      fullPath: '/dashboard/calls'
      preLoaderRoute: typeof DashboardCallsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketing/': {
      id: '/dashboard/marketing/'
      path: '/'
      fullPath: '/dashboard/marketing/'
      preLoaderRoute: typeof DashboardMarketingIndexRouteImport
      parentRoute: typeof DashboardMarketingRoute
    }
    '/dashboard/hrms/': {
      id: '/dashboard/hrms/'
      path: '/'
      fullPath: '/dashboard/hrms/'
      preLoaderRoute: typeof DashboardHrmsIndexRouteImport
      parentRoute: typeof DashboardHrmsRoute
    }
    '/dashboard/marketing/whatsapp': {
      id: '/dashboard/marketing/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/marketing/whatsapp'
      preLoaderRoute: typeof DashboardMarketingWhatsappRouteImport
      parentRoute: typeof DashboardMarketingRoute
    }
    '/dashboard/marketing/referral': {
      id: '/dashboard/marketing/referral'
      path: '/referral'
      fullPath: '/dashboard/marketing/referral'
      preLoaderRoute: typeof DashboardMarketingReferralRouteImport
      parentRoute: typeof DashboardMarketingRoute
    }
    '/dashboard/marketing/reels': {
      id: '/dashboard/marketing/reels'
      path: '/reels'
      fullPath: '/dashboard/marketing/reels'
      preLoaderRoute: typeof DashboardMarketingReelsRouteImport
      parentRoute: typeof DashboardMarketingRoute
    }
    '/dashboard/marketing/posts': {
      id: '/dashboard/marketing/posts'
      path: '/posts'
      fullPath: '/dashboard/marketing/posts'
      preLoaderRoute: typeof DashboardMarketingPostsRouteImport
      parentRoute: typeof DashboardMarketingRoute
    }
    '/dashboard/marketing/oneclick': {
      id: '/dashboard/marketing/oneclick'
      path: '/oneclick'
      fullPath: '/dashboard/marketing/oneclick'
      preLoaderRoute: typeof DashboardMarketingOneclickRouteImport
      parentRoute: typeof DashboardMarketingRoute
    }
    '/dashboard/marketing/card': {
      id: '/dashboard/marketing/card'
      path: '/card'
      fullPath: '/dashboard/marketing/card'
      preLoaderRoute: typeof DashboardMarketingCardRouteImport
      parentRoute: typeof DashboardMarketingRoute
    }
    '/dashboard/hrms/payroll': {
      id: '/dashboard/hrms/payroll'
      path: '/payroll'
      fullPath: '/dashboard/hrms/payroll'
      preLoaderRoute: typeof DashboardHrmsPayrollRouteImport
      parentRoute: typeof DashboardHrmsRoute
    }
    '/dashboard/hrms/billing': {
      id: '/dashboard/hrms/billing'
      path: '/billing'
      fullPath: '/dashboard/hrms/billing'
      preLoaderRoute: typeof DashboardHrmsBillingRouteImport
      parentRoute: typeof DashboardHrmsRoute
    }
    '/dashboard/hrms/attendance': {
      id: '/dashboard/hrms/attendance'
      path: '/attendance'
      fullPath: '/dashboard/hrms/attendance'
      preLoaderRoute: typeof DashboardHrmsAttendanceRouteImport
      parentRoute: typeof DashboardHrmsRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/pricing': {
      id: '/dashboard/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/dashboard/admin/pricing'
      preLoaderRoute: typeof DashboardAdminPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/payouts': {
      id: '/dashboard/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/dashboard/admin/payouts'
      preLoaderRoute: typeof DashboardAdminPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/marketing-media': {
      id: '/dashboard/admin/marketing-media'
      path: '/admin/marketing-media'
      fullPath: '/dashboard/admin/marketing-media'
      preLoaderRoute: typeof DashboardAdminMarketingMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/marketing': {
      id: '/dashboard/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/dashboard/admin/marketing'
      preLoaderRoute: typeof DashboardAdminMarketingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/leads': {
      id: '/dashboard/admin/leads'
      path: '/admin/leads'
      fullPath: '/dashboard/admin/leads'
      preLoaderRoute: typeof DashboardAdminLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hrms/payslips/': {
      id: '/dashboard/hrms/payslips/'
      path: '/payslips'
      fullPath: '/dashboard/hrms/payslips/'
      preLoaderRoute: typeof DashboardHrmsPayslipsIndexRouteImport
      parentRoute: typeof DashboardHrmsRoute
    }
    '/dashboard/my-leads/$id/apply': {
      id: '/dashboard/my-leads/$id/apply'
      path: '/$id/apply'
      fullPath: '/dashboard/my-leads/$id/apply'
      preLoaderRoute: typeof DashboardMyLeadsIdApplyRouteImport
      parentRoute: typeof DashboardMyLeadsRoute
    }
    '/dashboard/hrms/payslips/$id': {
      id: '/dashboard/hrms/payslips/$id'
      path: '/payslips/$id'
      fullPath: '/dashboard/hrms/payslips/$id'
      preLoaderRoute: typeof DashboardHrmsPayslipsIdRouteImport
      parentRoute: typeof DashboardHrmsRoute
    }
    '/dashboard/hrms/employees/$id': {
      id: '/dashboard/hrms/employees/$id'
      path: '/employees/$id'
      fullPath: '/dashboard/hrms/employees/$id'
      preLoaderRoute: typeof DashboardHrmsEmployeesIdRouteImport
      parentRoute: typeof DashboardHrmsRoute
    }
  }
}

interface DashboardHrmsRouteChildren {
  DashboardHrmsAttendanceRoute: typeof DashboardHrmsAttendanceRoute
  DashboardHrmsBillingRoute: typeof DashboardHrmsBillingRoute
  DashboardHrmsPayrollRoute: typeof DashboardHrmsPayrollRoute
  DashboardHrmsIndexRoute: typeof DashboardHrmsIndexRoute
  DashboardHrmsEmployeesIdRoute: typeof DashboardHrmsEmployeesIdRoute
  DashboardHrmsPayslipsIdRoute: typeof DashboardHrmsPayslipsIdRoute
  DashboardHrmsPayslipsIndexRoute: typeof DashboardHrmsPayslipsIndexRoute
}

const DashboardHrmsRouteChildren: DashboardHrmsRouteChildren = {
  DashboardHrmsAttendanceRoute: DashboardHrmsAttendanceRoute,
  DashboardHrmsBillingRoute: DashboardHrmsBillingRoute,
  DashboardHrmsPayrollRoute: DashboardHrmsPayrollRoute,
  DashboardHrmsIndexRoute: DashboardHrmsIndexRoute,
  DashboardHrmsEmployeesIdRoute: DashboardHrmsEmployeesIdRoute,
  DashboardHrmsPayslipsIdRoute: DashboardHrmsPayslipsIdRoute,
  DashboardHrmsPayslipsIndexRoute: DashboardHrmsPayslipsIndexRoute,
}

const DashboardHrmsRouteWithChildren = DashboardHrmsRoute._addFileChildren(
  DashboardHrmsRouteChildren,
)

interface DashboardMarketingRouteChildren {
  DashboardMarketingCardRoute: typeof DashboardMarketingCardRoute
  DashboardMarketingOneclickRoute: typeof DashboardMarketingOneclickRoute
  DashboardMarketingPostsRoute: typeof DashboardMarketingPostsRoute
  DashboardMarketingReelsRoute: typeof DashboardMarketingReelsRoute
  DashboardMarketingReferralRoute: typeof DashboardMarketingReferralRoute
  DashboardMarketingWhatsappRoute: typeof DashboardMarketingWhatsappRoute
  DashboardMarketingIndexRoute: typeof DashboardMarketingIndexRoute
}

const DashboardMarketingRouteChildren: DashboardMarketingRouteChildren = {
  DashboardMarketingCardRoute: DashboardMarketingCardRoute,
  DashboardMarketingOneclickRoute: DashboardMarketingOneclickRoute,
  DashboardMarketingPostsRoute: DashboardMarketingPostsRoute,
  DashboardMarketingReelsRoute: DashboardMarketingReelsRoute,
  DashboardMarketingReferralRoute: DashboardMarketingReferralRoute,
  DashboardMarketingWhatsappRoute: DashboardMarketingWhatsappRoute,
  DashboardMarketingIndexRoute: DashboardMarketingIndexRoute,
}

const DashboardMarketingRouteWithChildren =
  DashboardMarketingRoute._addFileChildren(DashboardMarketingRouteChildren)

interface DashboardMyLeadsRouteChildren {
  DashboardMyLeadsIdApplyRoute: typeof DashboardMyLeadsIdApplyRoute
}

const DashboardMyLeadsRouteChildren: DashboardMyLeadsRouteChildren = {
  DashboardMyLeadsIdApplyRoute: DashboardMyLeadsIdApplyRoute,
}

const DashboardMyLeadsRouteWithChildren =
  DashboardMyLeadsRoute._addFileChildren(DashboardMyLeadsRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCallsRoute: typeof DashboardCallsRoute
  DashboardCasesRoute: typeof DashboardCasesRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardHrmsRoute: typeof DashboardHrmsRouteWithChildren
  DashboardLeadboardRoute: typeof DashboardLeadboardRoute
  DashboardMarketingRoute: typeof DashboardMarketingRouteWithChildren
  DashboardMyLeadsRoute: typeof DashboardMyLeadsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardTrainingRoute: typeof DashboardTrainingRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardWorkspaceRoute: typeof DashboardWorkspaceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminLeadsRoute: typeof DashboardAdminLeadsRoute
  DashboardAdminMarketingRoute: typeof DashboardAdminMarketingRoute
  DashboardAdminMarketingMediaRoute: typeof DashboardAdminMarketingMediaRoute
  DashboardAdminPayoutsRoute: typeof DashboardAdminPayoutsRoute
  DashboardAdminPricingRoute: typeof DashboardAdminPricingRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCallsRoute: DashboardCallsRoute,
  DashboardCasesRoute: DashboardCasesRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardHrmsRoute: DashboardHrmsRouteWithChildren,
  DashboardLeadboardRoute: DashboardLeadboardRoute,
  DashboardMarketingRoute: DashboardMarketingRouteWithChildren,
  DashboardMyLeadsRoute: DashboardMyLeadsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardTrainingRoute: DashboardTrainingRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardWorkspaceRoute: DashboardWorkspaceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminLeadsRoute: DashboardAdminLeadsRoute,
  DashboardAdminMarketingRoute: DashboardAdminMarketingRoute,
  DashboardAdminMarketingMediaRoute: DashboardAdminMarketingMediaRoute,
  DashboardAdminPayoutsRoute: DashboardAdminPayoutsRoute,
  DashboardAdminPricingRoute: DashboardAdminPricingRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
