ALTER TABLE public.marketing_templates
  ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'evergreen',
  ADD COLUMN IF NOT EXISTS tags text[] NOT NULL DEFAULT ARRAY[]::text[],
  ADD COLUMN IF NOT EXISTS is_trending boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_daily boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS festival text,
  ADD COLUMN IF NOT EXISTS active_from date,
  ADD COLUMN IF NOT EXISTS active_until date;

CREATE INDEX IF NOT EXISTS idx_marketing_templates_category ON public.marketing_templates(category);
CREATE INDEX IF NOT EXISTS idx_marketing_templates_trending ON public.marketing_templates(is_trending) WHERE is_trending = true;
CREATE INDEX IF NOT EXISTS idx_marketing_templates_daily ON public.marketing_templates(is_daily) WHERE is_daily = true;

UPDATE public.marketing_templates
SET is_trending = true, category = 'trending'
WHERE id IN (SELECT id FROM public.marketing_templates WHERE kind='post' ORDER BY display_order LIMIT 3);

INSERT INTO public.marketing_templates
  (kind, product, name, headline, subheadline, body, cta, theme, category, festival, is_trending, display_order, enabled)
VALUES
  ('post','generic','Diwali Dhamaka Offer',
    'Diwali Dhamaka Loan Offer ✨','Lowest rates this festive season',
    'Personal Loan up to ₹15L · Approval in 24 hrs · Zero processing fee*','Apply This Diwali',
    '{"bg":"#3a0a1a","accent":"#fbbf24","text":"#fff7ed","pattern":"festive"}'::jsonb,
    'festival','diwali', true, 1, true),
  ('post','credit_card','Diwali Card Bonanza',
    'Diwali Credit Card Bonanza 🪔','5% cashback on festive shopping',
    'Lifetime free cards · Instant approval · Premium rewards','Get Your Card',
    '{"bg":"#1a0a2e","accent":"#f59e0b","text":"#ffffff","pattern":"festive"}'::jsonb,
    'festival','diwali', false, 2, true),
  ('post','generic','New Year New Loan',
    'New Year, New Goals 🎉','Start 2026 debt-free',
    'Consolidate · Refinance · Lower EMI · Apply in 5 minutes','Apply Now',
    '{"bg":"#0a1a3a","accent":"#22d3ee","text":"#ffffff","pattern":"waves"}'::jsonb,
    'festival','new_year', true, 3, true),
  ('post','home_loan','Holi Home Loan',
    'Color Your Dream Home 🎨','Holi special — 0% processing',
    'Home Loan @ 8.4%* · Tenure up to 30 years','Apply for Home Loan',
    '{"bg":"#2d0a3a","accent":"#ec4899","text":"#ffffff","pattern":"festive"}'::jsonb,
    'festival','holi', false, 4, true),
  ('post','business_loan','Independence Day BL',
    'Be Your Own Boss 🇮🇳','Independence Day special',
    'Business Loan up to ₹50L · No collateral · Quick disbursal','Grow Your Business',
    '{"bg":"#0a2e1a","accent":"#fb923c","text":"#ffffff","pattern":"diagonal"}'::jsonb,
    'festival','independence_day', false, 5, true),
  ('post','insurance','Raksha Bandhan Cover',
    'Tie a Knot of Protection 🪢','Raksha Bandhan special',
    'Term Insurance ₹1Cr cover @ ₹500/month · Tax savings up to ₹46,800','Protect Your Family',
    '{"bg":"#3a1a0a","accent":"#fde047","text":"#fff7ed","pattern":"shield"}'::jsonb,
    'festival','raksha_bandhan', false, 6, true),
  ('post','generic','Eid Mubarak Offer',
    'Eid Mubarak 🌙','Special festive rates',
    'Personal Loan · Business Loan · Home Loan — all under one roof','Apply Today',
    '{"bg":"#0a2e2a","accent":"#34d399","text":"#ffffff","pattern":"luxury"}'::jsonb,
    'festival','eid', false, 7, true),
  ('post','personal_loan','Daily — Quick PL',
    'Need ₹5L by tomorrow? 💸','24-hour approval guaranteed',
    'Personal Loan · Minimal docs · No guarantor needed','Apply Now',
    '{"bg":"#0c2340","accent":"#2dd4a8","text":"#ffffff","pattern":"diagonal"}'::jsonb,
    'daily',null, true, 10, true),
  ('post','credit_card','Daily — Free Credit Card',
    'Lifetime FREE Credit Card 💳','No annual fee. Ever.',
    'Up to 5% cashback · Instant approval · Premium lounge access','Get Free Card',
    '{"bg":"#1a0a2e","accent":"#a78bfa","text":"#ffffff","pattern":"luxury"}'::jsonb,
    'daily',null, true, 11, true),
  ('post','business_loan','Daily — Grow Business',
    'Scale your business 📈','Funding without collateral',
    'Up to ₹50L · 12% onwards · Disbursal in 48 hrs','Apply for BL',
    '{"bg":"#0a2e1a","accent":"#facc15","text":"#ffffff","pattern":"grid"}'::jsonb,
    'daily',null, false, 12, true),
  ('post','home_loan','Daily — Dream Home',
    'Own your dream home 🏡','Starting @ 8.4%* p.a.',
    'Loans up to ₹5Cr · Tenure 30 years · Balance transfer available','Check Eligibility',
    '{"bg":"#1a2e0a","accent":"#60a5fa","text":"#ffffff","pattern":"waves"}'::jsonb,
    'daily',null, false, 13, true),
  ('post','insurance','Daily — Term Plan',
    '₹1 Crore cover @ ₹500/mo 🛡️','Secure your family today',
    'Tax benefit · Critical illness rider · Pure protection','Get Insured',
    '{"bg":"#0a1a3a","accent":"#f87171","text":"#ffffff","pattern":"shield"}'::jsonb,
    'daily',null, false, 14, true),
  ('post','generic','Daily — Multi Product',
    'Money troubles? We solve them. 💼','Loans · Cards · Insurance',
    'One partner. Every financial product. Personalized for you.','Talk to Expert',
    '{"bg":"#2a0a3a","accent":"#34d399","text":"#ffffff","pattern":"dots"}'::jsonb,
    'daily',null, false, 15, true),
  ('post','msme','Daily — MSME Boost',
    'MSME Loan up to ₹2Cr 🏭','Govt-backed schemes',
    'Working capital · Equipment finance · Quick approval','Apply for MSME',
    '{"bg":"#3a1a0a","accent":"#fb923c","text":"#ffffff","pattern":"diagonal"}'::jsonb,
    'daily',null, false, 16, true);